from pathlib import Path
import re, shutil, zipfile, os
import numpy as np, pandas as pd
from datetime import datetime
np.random.seed(42)
BASE=Path('/mnt/data'); PROJ=BASE/'Lyra_Analytics_Project'
DIM=PROJ/'02_Dimensions'; FACT=PROJ/'03_Facts'; SQL=PROJ/'04_SQL'; DOC=PROJ/'05_Documentation'; CODE=PROJ/'06_Code'; QUAL=PROJ/'07_Quality'
FILES={
'out_raw':BASE/'Demo Hospital Outpatient Data_NHC.csv',
'out_clean':BASE/'Demo Hospital Outpatient Data Clean_NHC(2).csv',
'pat_exp':BASE/'Demo Patient Experience Data_NHC(3).csv',
'fac':BASE/'Demo Health Facilities Geo Data_NHC(3).csv',
'pharm':BASE/'Demo Pharmacy Sales Data.csv',
'medtxt':BASE/'1000 Generic Medication Names_NHC(3).txt'}
for k,p in list(FILES.items()):
    if not p.exists():
        # fallback
        alts={'out_clean':['Demo Hospital Outpatient Data Clean_NHC.csv'],'pat_exp':['Demo Patient Experience Data_NHC.csv'],'fac':['Demo Health Facilities Geo Data_NHC.csv'],'medtxt':['1000 Generic Medication Names_NHC.txt']}.get(k,[])
        for a in alts:
            if (BASE/a).exists(): FILES[k]=BASE/a; break
FX={'ZAR':1.0,'USD':18.5,'GBP':23.5,'AUD':12.2,'CAD':13.6}
COUNTRY=pd.DataFrame([[1,'US','United States','North America','United States','USD',0,0,'HIPAA-oriented privacy controls'],[2,'ZA','South Africa','Africa','Southern Africa','ZAR',0,1,'POPIA-oriented privacy controls'],[3,'UK','United Kingdom','Europe','Western Europe','GBP',1,0,'UK GDPR-oriented privacy controls'],[4,'AU','Australia','Asia-Pacific','Oceania','AUD',0,0,'Australian Privacy Act-oriented controls'],[5,'CA','Canada','North America','Canada','CAD',0,0,'PIPEDA-oriented privacy controls']],columns=['CountryKey','CountryCode','CountryName','GlobalRegion','SubRegion','CurrencyCode','GDPRApplicableFlag','POPIAApplicableFlag','PrivacyRegime'])
CLIENT=pd.DataFrame([[1,'CL001','Standard Bank','Financial Services','ZA','Enterprise EWP'],[2,'CL002','Discovery Limited','Financial Services','ZA','Integrated Wellbeing'],[3,'CL003','Vodacom','Telecommunications','ZA','Enterprise EWP'],[4,'CL004','MTN Group','Telecommunications','ZA','Enterprise EWP'],[5,'CL005','Sasol','Energy','ZA','Critical Incident Plus'],[6,'CL006','South African Public Sector Employer','Public Sector','ZA','Integrated Wellbeing'],[7,'CL007','US Technology Employer','Technology','US','Digital First'],[8,'CL008','US Healthcare Employer','Healthcare','US','Clinical Support'],[9,'CL009','US Financial Services Employer','Financial Services','US','Enterprise EWP'],[10,'CL010','UK Public Sector Employer','Public Sector','UK','Integrated Wellbeing'],[11,'CL011','UK Financial Services Employer','Financial Services','UK','Enterprise EWP'],[12,'CL012','Australian Mining Employer','Mining','AU','Critical Incident Plus'],[13,'CL013','Australian Healthcare Employer','Healthcare','AU','Clinical Support'],[14,'CL014','Canadian Technology Employer','Technology','CA','Digital First'],[15,'CL015','Canadian Retail Employer','Retail','CA','Enterprise EWP'],[16,'CL016','Global Logistics Employer','Logistics and Supply Chain','US','Enterprise EWP']],columns=['ClientCompanyKey','ClientCompanyID','ClientCompanyName','IndustrySectorName','CountryCode','ContractPackage'])
SERVICE=pd.DataFrame([[1,'ST001','Professional Telephone Counselling','Counselling','Remote'],[2,'ST002','In-Person Short-Term Solution Focused Counselling','Counselling','In-Person'],[3,'ST003','Work Life Services','Work-Life','Hybrid'],[4,'ST004','Managerial Counselling','Managerial','Remote'],[5,'ST005','Formal Referral and Conflict Mediation','Mediation','Hybrid'],[6,'ST006','Critical Incident Support','Crisis Support','Hybrid'],[7,'ST007','Wellbeing Coaching','Coaching','Remote'],[8,'ST008','Digital Solutions','Digital','Digital'],[9,'ST009','Crisis Management','Crisis Support','Hybrid'],[10,'ST010','Learning and Upskilling','Learning','Digital'],[11,'ST011','Organisational Development','Organisational','Hybrid'],[12,'ST012','Employee Wellness Days','Wellness Events','In-Person'],[13,'ST013','Organisational Performance Solutions','Organisational','Hybrid']],columns=['ServiceTypeKey','ServiceTypeCode','ServiceTypeName','ServiceCategory','DeliveryChannel'])
ISSUE=pd.DataFrame([[1,'IC001','Depression','Mental Health','High'],[2,'IC002','Anxiety','Mental Health','High'],[3,'IC003','Burnout','Workplace Wellbeing','Medium'],[4,'IC004','Financial Stress','Work Life','Medium'],[5,'IC005','Relationship Issues','Personal Wellbeing','Medium'],[6,'IC006','Substance Abuse','Mental Health','High'],[7,'IC007','Trauma','Crisis','High'],[8,'IC008','Work Conflict','Workplace Wellbeing','Medium'],[9,'IC009','Grief and Bereavement','Personal Wellbeing','High'],[10,'IC010','Legal Support','Work Life','Low'],[11,'IC011','Family Responsibility','Work Life','Medium'],[12,'IC012','Stress Management','Workplace Wellbeing','Medium'],[13,'IC013','Sleep Problems','Mental Health','Medium'],[14,'IC014','Career Uncertainty','Workplace Wellbeing','Low'],[15,'IC015','Critical Incident Trauma','Crisis','Critical']],columns=['IssueCategoryKey','IssueCategoryCode','IssueCategoryName','IssueGroup','DefaultRiskLevel'])
COUNS=pd.DataFrame([[i,f'CO{i:03d}',f'Counsellor {i:03d}',prof,lang,spec,1,1] for i,(prof,lang,spec) in enumerate([('Clinical Psychologist','English','Counselling'),('Registered Counsellor','English','Counselling'),('Social Worker','English','Work Life Services'),('Wellbeing Coach','English','Coaching'),('Trauma Counsellor','English','Crisis Support'),('Clinical Psychologist','Afrikaans','Counselling'),('Registered Counsellor','isiXhosa','Counselling'),('Registered Counsellor','isiZulu','Counselling'),('Mediator','English','Mediation'),('Organisational Psychologist','English','Organisational'),('Learning Facilitator','English','Learning'),('Executive Wellbeing Specialist','English','Executive Wellbeing')],1)],columns=['CounsellorKey','CounsellorID','CounsellorName','Profession','PrimaryLanguage','Specialisation','AccreditedFlag','ActiveFlag'])

def rc(p):
    with open(p,'rb') as f: return max(sum(1 for _ in f)-1,0)
def choose(vals,n,probs=None): return np.random.choice(vals,n,p=(np.array(probs)/np.sum(probs) if probs is not None else None))
def assign_from_groups(codes, groups):
    out=np.empty(len(codes), dtype=int)
    codes_arr=np.asarray(codes)
    for c, vals in groups.items():
        m=(codes_arr==c); out[m]=np.random.choice(vals, m.sum())
    return out
def save(df,name,folder=DIM):
    df.to_csv(folder/name,index=False); print(name,len(df))
def parse_med():
    pat=re.compile(r'^\s*(\d+)\.\s*(.*?)\s*-\s*(.*?)\s*$'); rows=[]
    terms=['antidepressant','serotonin','benzodiazepine','antipsychotic','mood stabilizer','anxiolytic','stimulant','sedative','hypnotic','melatonin','norepinephrine','tricyclic']
    with open(FILES['medtxt'],encoding='utf-8',errors='ignore') as f:
        for line in f:
            m=pat.match(line.strip())
            if not m: continue
            full=m.group(2).strip(); cls=m.group(3).strip(); sm=re.search(r'\((.*?)\)',full); name=re.sub(r'\s*\(.*?\)','',full).strip(); strength=sm.group(1) if sm else 'Unknown'; flag=int(any(t in cls.lower() for t in terms))
            rows.append([len(rows)+1,int(m.group(1)),name,full,strength,cls,flag,1])
    df=pd.DataFrame(rows,columns=['MedicationKey','SourceMedicationNumber','MedicationName','MedicationFullDescription','Strength','TherapeuticClass','MentalHealthMedicationFlag','ActiveFlag']).drop_duplicates(['MedicationName','Strength','TherapeuticClass']).reset_index(drop=True); df['MedicationKey']=np.arange(1,len(df)+1); return df

def setup():
    if PROJ.exists(): shutil.rmtree(PROJ)
    for d in [DIM,FACT,SQL,DOC,CODE,QUAL]: d.mkdir(parents=True, exist_ok=True)
    save(COUNTRY,'DimCountry.csv'); save(pd.DataFrame([[i,k,{'ZAR':'South African Rand','USD':'United States Dollar','GBP':'British Pound Sterling','AUD':'Australian Dollar','CAD':'Canadian Dollar'}[k],v,'Static interview demo rate','2026-01-01','9999-12-31',1] for i,(k,v) in enumerate(FX.items(),1)],columns=['CurrencyKey','CurrencyCode','CurrencyName','ExchangeRateToZAR','RateType','EffectiveFromDate','EffectiveToDate','IsCurrent']),'DimCurrency.csv')
    save(pd.DataFrame({'IndustrySectorKey':range(1,15),'IndustrySectorName':['Basic Materials','Technology','Consumer Services','Financial Services','Healthcare','Consumer Goods','Public Sector','Telecommunications','Industrial','Education','Retail','Logistics and Supply Chain','Energy','Mining'],'SectorActiveFlag':1}),'DimIndustrySector.csv')
    c=CLIENT.copy(); c['ContractStartDate']=pd.date_range('2024-01-01',periods=len(c),freq='18D'); c['ContractEndDate']='2027-12-31'; c['ContractStatus']='Active'; c['EffectiveFromDate']='2024-01-01'; c['EffectiveToDate']='9999-12-31'; c['IsCurrent']=1; save(c,'DimClientCompany.csv')
    save(SERVICE,'DimServiceType.csv'); save(ISSUE,'DimIssueCategory.csv'); save(pd.DataFrame([[1,'Low',0,39,'Self-service or routine follow-up'],[2,'Medium',40,69,'Managed support and follow-up'],[3,'High',70,89,'Priority counsellor follow-up'],[4,'Critical',90,100,'Immediate escalation']],columns=['RiskLevelKey','RiskLevel','RiskScoreMin','RiskScoreMax','RecommendedAction']),'DimRiskLevel.csv'); save(COUNS,'DimCounsellor.csv')
    dates=pd.date_range('2018-01-01','2027-12-31'); dd=pd.DataFrame({'FullDate':dates}); dd['DateKey']=dd.FullDate.dt.strftime('%Y%m%d').astype(int); dd['Year']=dd.FullDate.dt.year; dd['Quarter']=dd.FullDate.dt.quarter; dd['Month']=dd.FullDate.dt.month; dd['MonthName']=dd.FullDate.dt.month_name(); dd['WeekNumber']=dd.FullDate.dt.isocalendar().week.astype(int); dd['DayOfMonth']=dd.FullDate.dt.day; dd['DayName']=dd.FullDate.dt.day_name(); dd['IsWeekend']=dd.DayName.isin(['Saturday','Sunday']).astype(int); save(dd[['DateKey','FullDate','Year','Quarter','Month','MonthName','WeekNumber','DayOfMonth','DayName','IsWeekend']],'DimDate.csv')
    save(parse_med(),'DimMedication.csv')

def facility():
    df=pd.read_csv(FILES['fac']); n=len(df); df.insert(0,'FacilityKey',np.arange(1,n+1)); df['CountryCode']=choose(['US','ZA','UK','AU','CA'],n,[.55,.20,.10,.08,.07]); df=df.merge(COUNTRY[['CountryCode','CountryName','GlobalRegion','SubRegion','CurrencyCode','PrivacyRegime']],on='CountryCode',how='left')
    prov={'US':['California','New York','Texas','Florida','Washington'],'ZA':['Western Cape','Gauteng','KwaZulu-Natal','Eastern Cape','Free State'],'UK':['England','Scotland','Wales','Northern Ireland'],'AU':['New South Wales','Victoria','Queensland','Western Australia'],'CA':['Ontario','British Columbia','Quebec','Alberta']}; city={'US':['Los Angeles','New York','Austin','Miami','Seattle'],'ZA':['Cape Town','Johannesburg','Durban','Pretoria','Bloemfontein'],'UK':['London','Manchester','Edinburgh','Cardiff','Belfast'],'AU':['Sydney','Melbourne','Brisbane','Perth','Adelaide'],'CA':['Toronto','Vancouver','Montreal','Calgary','Ottawa']}
    df['ProvinceState']=[np.random.choice(prov[c]) for c in df.CountryCode]; df['City']=[np.random.choice(city[c]) for c in df.CountryCode]; df['LyraFacilityType']=choose(['Telephone Counselling Centre','In-Person Counselling Centre','Digital Care Hub','Corporate Wellness Site','Critical Incident Response Centre'],n,[.30,.25,.20,.15,.10]); df['ActiveFlag']=1; save(df,'DimFacilityGeography.csv',FACT); return df

def sessions(fac):
    out=FACT/'FactCounsellingSessions.csv'; header=True; start_key=1; cg=CLIENT.groupby('CountryCode')['ClientCompanyKey'].apply(lambda s:s.to_numpy()).to_dict(); fg=fac.groupby('CountryCode')['FacilityKey'].apply(lambda s:s.to_numpy()).to_dict()
    for chunk in pd.read_csv(FILES['out_raw'],chunksize=200000,low_memory=False):
        n=len(chunk); df=chunk.copy(); df.insert(0,'SessionKey',np.arange(start_key,start_key+n)); df.insert(1,'SessionID','SES'+pd.Series(np.arange(start_key,start_key+n)).astype(str).str.zfill(9)); start_key+=n
        df['Visit_Date']=pd.to_datetime(df.Visit_Date,errors='coerce'); df['DateKey']=df.Visit_Date.dt.strftime('%Y%m%d').astype('Int64'); df['EmployeeNaturalKey']='EMP'+df.Patient_ID.astype(str).str.zfill(10); df['CountryCode']=choose(['US','ZA','UK','AU','CA'],n,[.55,.20,.10,.08,.07]); df=df.merge(COUNTRY[['CountryCode','CountryKey','CountryName','GlobalRegion','CurrencyCode','PrivacyRegime']],on='CountryCode',how='left'); df['ClientCompanyKey']=assign_from_groups(df.CountryCode.values,cg); df=df.merge(CLIENT[['ClientCompanyKey','ClientCompanyName','IndustrySectorName','ContractPackage']],on='ClientCompanyKey',how='left'); df['ServiceTypeKey']=choose(SERVICE.ServiceTypeKey.values,n,[.34,.18,.10,.07,.04,.05,.10,.06,.02,.02,.01,.005,.005]); df=df.merge(SERVICE[['ServiceTypeKey','ServiceTypeName','ServiceCategory','DeliveryChannel']],on='ServiceTypeKey',how='left'); df['IssueCategoryKey']=choose(ISSUE.IssueCategoryKey.values,n,[.20,.18,.14,.08,.08,.03,.05,.08,.04,.03,.03,.04,.02,.01,.01]); df=df.merge(ISSUE[['IssueCategoryKey','IssueCategoryName','IssueGroup','DefaultRiskLevel']],on='IssueCategoryKey',how='left'); df['CounsellorKey']=choose(COUNS.CounsellorKey.values,n); df['FacilityKey']=assign_from_groups(df.CountryCode.values,fg); df['SessionDurationMinutes']=(pd.to_numeric(df.Consultation,errors='coerce').fillna(0)+pd.to_numeric(df.Nursing,errors='coerce').fillna(0)*.2).round().astype(int).clip(10,240); base=df.DefaultRiskLevel.map({'Low':25,'Medium':55,'High':78,'Critical':94}).fillna(55); df['RiskScore']=(base+np.random.normal(0,8,n)).round().astype(int).clip(0,100); df['RiskLevel']=pd.cut(df.RiskScore,[-1,39,69,89,100],labels=['Low','Medium','High','Critical']).astype(str); df['FollowUpRequiredFlag']=(df.RiskScore>=60).astype(int); df['EmergencyEscalationFlag']=(df.RiskScore>=90).astype(int); df['CaseResolvedFlag']=np.where(df.RiskScore<70,choose([0,1],n,[.25,.75]),choose([0,1],n,[.55,.45])); df['RevenueAmountLocal']=pd.to_numeric(df.Total_Cost,errors='coerce').fillna(0).round(2); df['RevenueAmountZAR']=(df.RevenueAmountLocal*df.CurrencyCode.map(FX).fillna(1)).round(2); df['SessionCount']=1; df['LoadDTS']=datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        cols=['SessionKey','SessionID','Visit_Date','DateKey','EmployeeNaturalKey','Patient_ID','Age','Gender','Diagnosis','Has_Insurance','Postcode','CountryKey','CountryCode','CountryName','GlobalRegion','CurrencyCode','PrivacyRegime','ClientCompanyKey','ClientCompanyName','IndustrySectorName','ContractPackage','FacilityKey','ServiceTypeKey','ServiceTypeName','ServiceCategory','DeliveryChannel','IssueCategoryKey','IssueCategoryName','IssueGroup','CounsellorKey','SessionDurationMinutes','RiskScore','RiskLevel','FollowUpRequiredFlag','EmergencyEscalationFlag','CaseResolvedFlag','SessionCount','RevenueAmountLocal','RevenueAmountZAR','Registration','Nursing','Laboratory','Consultation','Pharmacy','LoadDTS']
        df[cols].to_csv(out,index=False,mode='w' if header else 'a',header=header); header=False; print('sessions chunk',n)

def med_sales():
    out=FACT/'FactMedicationSales.csv'; header=True; start=1; med=pd.read_csv(DIM/'DimMedication.csv'); cg=CLIENT.groupby('CountryCode')['ClientCompanyKey'].apply(lambda s:s.to_numpy()).to_dict()
    for chunk in pd.read_csv(FILES['pharm'],chunksize=200000,low_memory=False):
        n=len(chunk); df=chunk.copy(); df.columns=[c.replace(' ','_') for c in df.columns]; df.insert(0,'MedicationSalesKey',np.arange(start,start+n)); df.insert(1,'MedicationSalesID','MEDSALE'+pd.Series(np.arange(start,start+n)).astype(str).str.zfill(9)); start+=n; df['Date_Sold']=pd.to_datetime(df.Date_Sold,errors='coerce'); df['DateKey']=df.Date_Sold.dt.strftime('%Y%m%d').astype('Int64'); df['CountryCode']=choose(['US','ZA','UK','AU','CA'],n,[.55,.20,.10,.08,.07]); df=df.merge(COUNTRY[['CountryCode','CountryKey','CountryName','GlobalRegion','CurrencyCode']],on='CountryCode',how='left'); df=df.merge(med[['MedicationKey','MedicationFullDescription','MedicationName','TherapeuticClass','MentalHealthMedicationFlag']],left_on=['Med_name','Med_class'],right_on=['MedicationFullDescription','TherapeuticClass'],how='left'); miss=df.MedicationKey.isna(); df.loc[miss,'MedicationKey']=0; df.loc[miss,'MedicationName']=df.loc[miss,'Med_name']; df.loc[miss,'TherapeuticClass']=df.loc[miss,'Med_class']; df.loc[miss,'MentalHealthMedicationFlag']=df.loc[miss,'Med_class'].astype(str).str.lower().str.contains('antidepressant|benzodiazepine|antipsychotic|mood|anxiolytic|stimulant|serotonin|norepinephrine|sedative|hypnotic',regex=True).astype(int); df['MedicationKey']=df.MedicationKey.astype(int); df['ClientCompanyKey']=assign_from_groups(df.CountryCode.values,cg); df=df.merge(CLIENT[['ClientCompanyKey','ClientCompanyName','IndustrySectorName']],on='ClientCompanyKey',how='left'); df['MedicationSalesAmountLocal']=(pd.to_numeric(df.Quantity_Sold,errors='coerce').fillna(0)*pd.to_numeric(df.Price,errors='coerce').fillna(0)).round(2); df['MedicationSalesAmountZAR']=(df.MedicationSalesAmountLocal*df.CurrencyCode.map(FX).fillna(1)).round(2); df['PrescriptionRequiredFlag']=df.TherapeuticClass.astype(str).str.lower().str.contains('antidepressant|benzodiazepine|antipsychotic|opioid|mood|stimulant|anxiolytic',regex=True).astype(int); df['TreatmentType']=np.where(df.MentalHealthMedicationFlag==1,'Mental Health Medication','General Healthcare Medication'); df['LoadDTS']=datetime.now().strftime('%Y-%m-%d %H:%M:%S'); df.to_csv(out,index=False,mode='w' if header else 'a',header=header); header=False; print('med chunk',n)

def exp():
    df=pd.read_csv(FILES['pat_exp']); n=len(df); df.columns=[c.replace(' ','_').replace('(','').replace(')','') for c in df.columns]; df.insert(0,'ExperienceKey',np.arange(1,n+1)); df.insert(1,'ExperienceID','EXP'+pd.Series(np.arange(1,n+1)).astype(str).str.zfill(9)); df['Feedback_Date']=pd.to_datetime(df.Feedback_Date,errors='coerce'); df['DateKey']=df.Feedback_Date.dt.strftime('%Y%m%d').astype('Int64'); df['CountryCode']=choose(['US','ZA','UK','AU','CA'],n,[.55,.20,.10,.08,.07]); df=df.merge(COUNTRY[['CountryCode','CountryKey','CountryName','GlobalRegion','CurrencyCode']],on='CountryCode',how='left'); df['ServiceTypeKey']=choose(SERVICE.ServiceTypeKey.values,n); df=df.merge(SERVICE[['ServiceTypeKey','ServiceTypeName','ServiceCategory','DeliveryChannel']],on='ServiceTypeKey',how='left'); df['IssueCategoryKey']=choose(ISSUE.IssueCategoryKey.values,n,[.20,.18,.14,.08,.08,.03,.05,.08,.04,.03,.03,.04,.02,.01,.01]); df=df.merge(ISSUE[['IssueCategoryKey','IssueCategoryName','IssueGroup']],on='IssueCategoryKey',how='left'); df['StaffRating10']=(pd.to_numeric(df.Staff_Rating,errors='coerce')*2).clip(1,10); df['SpeedRating10']=(pd.to_numeric(df.Speed_Rating,errors='coerce')*2).clip(1,10); df['SatisfactionScore']=((df.StaffRating10*.6)+(df.SpeedRating10*.4)).round(1); df['NetPromoterScore']=np.where(df.SatisfactionScore>=9,choose([9,10],n,[.45,.55]),np.where(df.SatisfactionScore>=7,choose([7,8],n),choose([0,1,2,3,4,5,6],n))); df['OutcomeBeforeScore']=choose([2,3,4,5,6,7],n,[.12,.18,.22,.22,.16,.10]); df['OutcomeAfterScore']=np.minimum(10,df.OutcomeBeforeScore+choose([0,1,2,3],n,[.15,.35,.35,.15])); df['ImprovementScore']=df.OutcomeAfterScore-df.OutcomeBeforeScore; df['WouldRecommendFlag']=(df.NetPromoterScore>=8).astype(int); df['ComplaintFlag']=(df.SatisfactionScore<=5).astype(int); df['LoadDTS']=datetime.now().strftime('%Y-%m-%d %H:%M:%S'); save(df,'FactPatientExperience.csv',FACT)

def digital(n=1000000):
    out=FACT/'FactDigitalEngagement.csv'; header=True; start=1; cg=CLIENT.groupby('CountryCode')['ClientCompanyKey'].apply(lambda s:s.to_numpy()).to_dict()
    for size in [200000]*5:
        dates=pd.to_datetime(np.random.randint(pd.Timestamp('2022-01-01').value//10**9,pd.Timestamp('2026-12-31').value//10**9,size),unit='s').normalize(); df=pd.DataFrame({'DigitalEngagementKey':np.arange(start,start+size),'DigitalEngagementID':'DIG'+pd.Series(np.arange(start,start+size)).astype(str).str.zfill(9),'EngagementDate':dates}); start+=size; df['DateKey']=df.EngagementDate.dt.strftime('%Y%m%d').astype(int); df['CountryCode']=choose(['US','ZA','UK','AU','CA'],size,[.55,.20,.10,.08,.07]); df=df.merge(COUNTRY[['CountryCode','CountryKey','CountryName','GlobalRegion','CurrencyCode']],on='CountryCode',how='left'); df['ClientCompanyKey']=assign_from_groups(df.CountryCode.values,cg); df['ServiceTypeKey']=choose(SERVICE.ServiceTypeKey.values,size,[.18,.02,.10,.02,.01,.02,.12,.35,.01,.12,.02,.02,.01]); df['IssueCategoryKey']=choose(ISSUE.IssueCategoryKey.values,size,[.20,.18,.14,.08,.08,.03,.05,.08,.04,.03,.03,.04,.02,.01,.01]); df['DigitalChannel']=choose(['Mobile App','Web Portal','Live Chat','Push-to-Call','Self-Service Article','Video Content'],size,[.35,.22,.13,.10,.15,.05]); df['EngagementType']=choose(['Article View','Self Assessment','Live Chat','Call Request','Video View','Resource Download'],size,[.28,.18,.14,.12,.16,.12]); df['EngagementDurationSeconds']=np.random.randint(30,1801,size); df['CompletedEngagementFlag']=choose([0,1],size,[.22,.78]); df['ConversionToCounsellingFlag']=choose([0,1],size,[.88,.12]); df['LoadDTS']=datetime.now().strftime('%Y-%m-%d %H:%M:%S'); df.to_csv(out,index=False,mode='w' if header else 'a',header=header); header=False; print('digital chunk',size)

def scd():
    sample=pd.read_csv(FACT/'FactCounsellingSessions.csv',usecols=['EmployeeNaturalKey','Age','Gender','CountryCode'],nrows=100000).drop_duplicates('EmployeeNaturalKey'); n=len(sample); emp=sample.copy(); emp.insert(0,'EmployeeKey',np.arange(1,n+1)); emp['AgeBand']=pd.cut(emp.Age,[0,24,34,44,54,64,200],labels=['18-24','25-34','35-44','45-54','55-64','65+']).astype(str); emp['EmploymentLevel']=choose(['Junior','Intermediate','Senior','Manager','Executive'],n,[.18,.30,.28,.18,.06]); emp['Department']=choose(['Finance','Information Technology','Human Resources','Operations','Sales','Marketing','Customer Service','Legal','Supply Chain'],n); emp['EffectiveFromDate']='2024-01-01'; emp['EffectiveToDate']='9999-12-31'; emp['IsCurrent']=1; emp['ChangeReason']='Initial Load'; emp['HashValue']=pd.util.hash_pandas_object(emp[['EmployeeNaturalKey','AgeBand','Gender','EmploymentLevel','Department','CountryCode']].astype(str),index=False).astype(str); save(emp,'DimEmployee_SCD2.csv',DIM)
    types=['Service Delivery','Analytics','Marketing','Research','Data Sharing']; con=emp[['EmployeeNaturalKey','CountryCode']].loc[emp.index.repeat(len(types))].reset_index(drop=True); con.insert(0,'ConsentKey',np.arange(1,len(con)+1)); con['ConsentType']=types*len(emp); con['ConsentStatus']=choose(['Granted','Declined'],len(con),[.88,.12]); con['ConsentChannel']=choose(['Mobile App','Web Portal','Call Centre','HR Upload'],len(con)); con['EffectiveFromDate']='2024-01-01'; con['EffectiveToDate']='9999-12-31'; con['IsCurrent']=1; con['ChangeReason']='Initial Consent'; con['HashValue']=pd.util.hash_pandas_object(con[['EmployeeNaturalKey','ConsentType','ConsentStatus','ConsentChannel']].astype(str),index=False).astype(str); save(con,'DimConsent_SCD2.csv',DIM)

def docs_zip():
    counts=[]
    for folder in [DIM,FACT]:
        for f in folder.glob('*.csv'): counts.append({'TableName':f.stem,'RowCount':rc(f),'ColumnCount':len(pd.read_csv(f,nrows=0).columns)})
    pd.DataFrame(counts).to_csv(QUAL/'Generated_Table_Row_Counts.csv',index=False)
    pd.DataFrame([{'SourceFile':v.name,'RowCount':rc(v) if v.suffix=='.csv' else sum(1 for line in open(v,encoding='utf-8',errors='ignore') if line.strip())} for v in FILES.values()]).to_csv(QUAL/'Source_Row_Counts.csv',index=False)
    lines=['-- LYRA WELLBEING ANALYTICS SNOWFLAKE DDL','CREATE DATABASE IF NOT EXISTS LYRA_ANALYTICS;','CREATE SCHEMA IF NOT EXISTS LYRA_ANALYTICS.DIM;','CREATE SCHEMA IF NOT EXISTS LYRA_ANALYTICS.FACT;','']
    for folder,schema in [(DIM,'DIM'),(FACT,'FACT')]:
        for f in sorted(folder.glob('*.csv')):
            df=pd.read_csv(f,nrows=25,low_memory=False); lines.append(f'CREATE OR REPLACE TABLE LYRA_ANALYTICS.{schema}.{f.stem.upper()} ('); col=[]
            for c in df.columns:
                d=str(df[c].dtype).lower(); typ='NUMBER(38,0)' if 'int' in d else ('NUMBER(18,4)' if 'float' in d else ('TIMESTAMP_NTZ' if 'datetime' in d else 'VARCHAR'))
                col.append(f'    {c.upper()} {typ}')
            lines.append(',\n'.join(col)); lines.append(');\n')
    (SQL/'01_Create_Lyra_Snowflake_Tables.sql').write_text('\n'.join(lines),encoding='utf-8')
    md='# Lyra Wellbeing Analytics Additional Data Model\n\nThe pack adds Lyra-relevant mental health, employee wellbeing, client-company, country, currency, consent, SCD Type 2 and digital engagement data to your supplied healthcare files.\n\n## Core Tables\n\n| Table | Rows | Purpose |\n|---|---:|---|\n'
    for r in counts: md+=f"| {r['TableName']} | {r['RowCount']:,} | Generated/enriched analytics table |\n"
    md+='''\n## ERD\n```text\nDimDate ─┬─ FactCounsellingSessions ─ DimServiceType ─ DimIssueCategory\n         │             ├ DimClientCompany ─ DimCountry ─ DimCurrency\n         │             ├ DimFacilityGeography\n         │             ├ DimCounsellor\n         │             ├ DimEmployee_SCD2\n         │             └ DimConsent_SCD2\n         ├─ FactMedicationSales ─ DimMedication\n         ├─ FactDigitalEngagement\n         └─ FactPatientExperience\n```\n\nThis design is suitable for Snowflake, dbt, Snowpark, Tableau and Power BI demonstration work.\n'''
    (DOC/'Data_Model_and_Project_Guide.md').write_text(md,encoding='utf-8')
    shutil.copy2(__file__,CODE/'build_project_chunked.py')
    zpath=BASE/'Lyra_Analytics_Project.zip'
    if zpath.exists(): zpath.unlink()
    with zipfile.ZipFile(zpath,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
        for f in PROJ.rglob('*'):
            if f.is_file(): z.write(f,f.relative_to(PROJ.parent))
    print('ZIP_DONE',zpath,zpath.stat().st_size/1024/1024)

def main():
    setup(); fac=facility(); sessions(fac); exp(); med_sales(); digital(); scd(); docs_zip()
if __name__=='__main__': main()
