-- LYRA WELLBEING ANALYTICS SNOWFLAKE DDL
CREATE DATABASE IF NOT EXISTS LYRA_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS LYRA_ANALYTICS.DIM;
CREATE SCHEMA IF NOT EXISTS LYRA_ANALYTICS.FACT;

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMCLIENTCOMPANY (
    CLIENTCOMPANYKEY NUMBER(38,0),
    CLIENTCOMPANYID VARCHAR,
    CLIENTCOMPANYNAME VARCHAR,
    INDUSTRYSECTORNAME VARCHAR,
    COUNTRYCODE VARCHAR,
    CONTRACTPACKAGE VARCHAR,
    CONTRACTSTARTDATE VARCHAR,
    CONTRACTENDDATE VARCHAR,
    CONTRACTSTATUS VARCHAR,
    EFFECTIVEFROMDATE VARCHAR,
    EFFECTIVETODATE VARCHAR,
    ISCURRENT NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMCONSENT_SCD2 (
    CONSENTKEY NUMBER(38,0),
    EMPLOYEENATURALKEY VARCHAR,
    COUNTRYCODE VARCHAR,
    CONSENTTYPE VARCHAR,
    CONSENTSTATUS VARCHAR,
    CONSENTCHANNEL VARCHAR,
    EFFECTIVEFROMDATE VARCHAR,
    EFFECTIVETODATE VARCHAR,
    ISCURRENT NUMBER(38,0),
    CHANGEREASON VARCHAR,
    HASHVALUE NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMCOUNSELLOR (
    COUNSELLORKEY NUMBER(38,0),
    COUNSELLORID VARCHAR,
    COUNSELLORNAME VARCHAR,
    PROFESSION VARCHAR,
    PRIMARYLANGUAGE VARCHAR,
    SPECIALISATION VARCHAR,
    ACCREDITEDFLAG NUMBER(38,0),
    ACTIVEFLAG NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMCOUNTRY (
    COUNTRYKEY NUMBER(38,0),
    COUNTRYCODE VARCHAR,
    COUNTRYNAME VARCHAR,
    GLOBALREGION VARCHAR,
    SUBREGION VARCHAR,
    CURRENCYCODE VARCHAR,
    GDPRAPPLICABLEFLAG NUMBER(38,0),
    POPIAAPPLICABLEFLAG NUMBER(38,0),
    PRIVACYREGIME VARCHAR
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMCURRENCY (
    CURRENCYKEY NUMBER(38,0),
    CURRENCYCODE VARCHAR,
    CURRENCYNAME VARCHAR,
    EXCHANGERATETOZAR NUMBER(18,4),
    RATETYPE VARCHAR,
    EFFECTIVEFROMDATE VARCHAR,
    EFFECTIVETODATE VARCHAR,
    ISCURRENT NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMDATE (
    DATEKEY NUMBER(38,0),
    FULLDATE VARCHAR,
    YEAR NUMBER(38,0),
    QUARTER NUMBER(38,0),
    MONTH NUMBER(38,0),
    MONTHNAME VARCHAR,
    WEEKNUMBER NUMBER(38,0),
    DAYOFMONTH NUMBER(38,0),
    DAYNAME VARCHAR,
    ISWEEKEND NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMEMPLOYEE_SCD2 (
    EMPLOYEEKEY NUMBER(38,0),
    EMPLOYEENATURALKEY VARCHAR,
    AGE NUMBER(38,0),
    GENDER VARCHAR,
    COUNTRYCODE VARCHAR,
    AGEBAND VARCHAR,
    EMPLOYMENTLEVEL VARCHAR,
    DEPARTMENT VARCHAR,
    EFFECTIVEFROMDATE VARCHAR,
    EFFECTIVETODATE VARCHAR,
    ISCURRENT NUMBER(38,0),
    CHANGEREASON VARCHAR,
    HASHVALUE NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMINDUSTRYSECTOR (
    INDUSTRYSECTORKEY NUMBER(38,0),
    INDUSTRYSECTORNAME VARCHAR,
    SECTORACTIVEFLAG NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMISSUECATEGORY (
    ISSUECATEGORYKEY NUMBER(38,0),
    ISSUECATEGORYCODE VARCHAR,
    ISSUECATEGORYNAME VARCHAR,
    ISSUEGROUP VARCHAR,
    DEFAULTRISKLEVEL VARCHAR
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMMEDICATION (
    MEDICATIONKEY NUMBER(38,0),
    SOURCEMEDICATIONNUMBER NUMBER(38,0),
    MEDICATIONNAME VARCHAR,
    MEDICATIONFULLDESCRIPTION VARCHAR,
    STRENGTH VARCHAR,
    THERAPEUTICCLASS VARCHAR,
    MENTALHEALTHMEDICATIONFLAG NUMBER(38,0),
    ACTIVEFLAG NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMRISKLEVEL (
    RISKLEVELKEY NUMBER(38,0),
    RISKLEVEL VARCHAR,
    RISKSCOREMIN NUMBER(38,0),
    RISKSCOREMAX NUMBER(38,0),
    RECOMMENDEDACTION VARCHAR
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.DIM.DIMSERVICETYPE (
    SERVICETYPEKEY NUMBER(38,0),
    SERVICETYPECODE VARCHAR,
    SERVICETYPENAME VARCHAR,
    SERVICECATEGORY VARCHAR,
    DELIVERYCHANNEL VARCHAR
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.FACT.DIMFACILITYGEOGRAPHY (
    FACILITYKEY NUMBER(38,0),
    FACILITY TYPE VARCHAR,
    LATITUDE NUMBER(18,4),
    LONGITUDE NUMBER(18,4),
    COUNTRYCODE VARCHAR,
    COUNTRYNAME VARCHAR,
    GLOBALREGION VARCHAR,
    SUBREGION VARCHAR,
    CURRENCYCODE VARCHAR,
    PRIVACYREGIME VARCHAR,
    PROVINCESTATE VARCHAR,
    CITY VARCHAR,
    LYRAFACILITYTYPE VARCHAR,
    ACTIVEFLAG NUMBER(38,0)
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.FACT.FACTCOUNSELLINGSESSIONS (
    SESSIONKEY NUMBER(38,0),
    SESSIONID VARCHAR,
    VISIT_DATE VARCHAR,
    DATEKEY NUMBER(38,0),
    EMPLOYEENATURALKEY VARCHAR,
    PATIENT_ID NUMBER(38,0),
    AGE NUMBER(38,0),
    GENDER VARCHAR,
    DIAGNOSIS VARCHAR,
    HAS_INSURANCE VARCHAR,
    POSTCODE NUMBER(38,0),
    COUNTRYKEY NUMBER(38,0),
    COUNTRYCODE VARCHAR,
    COUNTRYNAME VARCHAR,
    GLOBALREGION VARCHAR,
    CURRENCYCODE VARCHAR,
    PRIVACYREGIME VARCHAR,
    CLIENTCOMPANYKEY NUMBER(38,0),
    CLIENTCOMPANYNAME VARCHAR,
    INDUSTRYSECTORNAME VARCHAR,
    CONTRACTPACKAGE VARCHAR,
    FACILITYKEY NUMBER(38,0),
    SERVICETYPEKEY NUMBER(38,0),
    SERVICETYPENAME VARCHAR,
    SERVICECATEGORY VARCHAR,
    DELIVERYCHANNEL VARCHAR,
    ISSUECATEGORYKEY NUMBER(38,0),
    ISSUECATEGORYNAME VARCHAR,
    ISSUEGROUP VARCHAR,
    COUNSELLORKEY NUMBER(38,0),
    SESSIONDURATIONMINUTES NUMBER(38,0),
    RISKSCORE NUMBER(38,0),
    RISKLEVEL VARCHAR,
    FOLLOWUPREQUIREDFLAG NUMBER(38,0),
    EMERGENCYESCALATIONFLAG NUMBER(38,0),
    CASERESOLVEDFLAG NUMBER(38,0),
    SESSIONCOUNT NUMBER(38,0),
    REVENUEAMOUNTLOCAL NUMBER(18,4),
    REVENUEAMOUNTZAR NUMBER(18,4),
    REGISTRATION NUMBER(38,0),
    NURSING NUMBER(38,0),
    LABORATORY NUMBER(38,0),
    CONSULTATION NUMBER(38,0),
    PHARMACY NUMBER(38,0),
    LOADDTS VARCHAR
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.FACT.FACTMEDICATIONSALES (
    MEDICATIONSALESKEY NUMBER(38,0),
    MEDICATIONSALESID VARCHAR,
    DATE_SOLD VARCHAR,
    MED_NAME VARCHAR,
    MED_CLASS VARCHAR,
    QUANTITY_SOLD NUMBER(38,0),
    PRICE NUMBER(18,4),
    DATEKEY NUMBER(38,0),
    COUNTRYCODE VARCHAR,
    COUNTRYKEY NUMBER(38,0),
    COUNTRYNAME VARCHAR,
    GLOBALREGION VARCHAR,
    CURRENCYCODE VARCHAR,
    MENTALHEALTHMEDICATIONFLAG NUMBER(38,0),
    THERAPEUTICCLASS VARCHAR,
    MEDICATIONNAME VARCHAR,
    MEDICATIONKEY NUMBER(38,0),
    CLIENTCOMPANYKEY NUMBER(38,0),
    CLIENTCOMPANYNAME VARCHAR,
    INDUSTRYSECTORNAME VARCHAR,
    MEDICATIONSALESAMOUNTLOCAL NUMBER(18,4),
    MEDICATIONSALESAMOUNTZAR NUMBER(18,4),
    PRESCRIPTIONREQUIREDFLAG NUMBER(38,0),
    TREATMENTTYPE VARCHAR,
    LOADDTS VARCHAR
);

CREATE OR REPLACE TABLE LYRA_ANALYTICS.FACT.FACTPATIENTEXPERIENCE (
    EXPERIENCEKEY NUMBER(38,0),
    EXPERIENCEID VARCHAR,
    UNNAMED:_0 NUMBER(38,0),
    ENTRY_CODE NUMBER(38,0),
    FEEDBACK_DATE VARCHAR,
    PATIENT_AGE NUMBER(38,0),
    STAFF_RATING NUMBER(38,0),
    SPEED_RATING NUMBER(38,0),
    WAIT_TIME_MINUTES NUMBER(38,0),
    TEST_TYPE VARCHAR,
    REVIEW VARCHAR,
    DATEKEY NUMBER(38,0),
    COUNTRYCODE VARCHAR,
    COUNTRYKEY NUMBER(38,0),
    COUNTRYNAME VARCHAR,
    GLOBALREGION VARCHAR,
    CURRENCYCODE VARCHAR,
    SERVICETYPEKEY NUMBER(38,0),
    SERVICETYPENAME VARCHAR,
    SERVICECATEGORY VARCHAR,
    DELIVERYCHANNEL VARCHAR,
    ISSUECATEGORYKEY NUMBER(38,0),
    ISSUECATEGORYNAME VARCHAR,
    ISSUEGROUP VARCHAR,
    STAFFRATING10 NUMBER(38,0),
    SPEEDRATING10 NUMBER(38,0),
    SATISFACTIONSCORE NUMBER(18,4),
    NETPROMOTERSCORE NUMBER(38,0),
    OUTCOMEBEFORESCORE NUMBER(38,0),
    OUTCOMEAFTERSCORE NUMBER(38,0),
    IMPROVEMENTSCORE NUMBER(38,0),
    WOULDRECOMMENDFLAG NUMBER(38,0),
    COMPLAINTFLAG NUMBER(38,0),
    LOADDTS VARCHAR
);
